services:
  db:
    ports:
      - 5432:5432
    container_name: postgresql_container
    image: postgres:latest
    environment:
      - POSTGRES_DB=FlightSearchDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123!@#OP
    volumes:
      - C:\postgres_datapart:/var/lib/postgresql/data
    restart: always
  web:
    image: jehad950/flight_search_rest_api:v1.0
    build: .
    container_name: flight_search_rest_api_container
    ports:
      - 8080:8080
    environment:
      db-url: jdbc:postgresql://db:5432/FlightSearchDB
      db-user: postgres
      db-password: 123!@#OP
    depends_on:
      - db
    restart: always

#  docker compose -f .\docker-compose.yaml up -d
#  docker-compose up
#  docker-compose down

#  docker tag jehad950/flight_search_rest_api:v1.0 jehad950/flight_search_rest_api:v1.0
#  docker push jehad950/flight_search_rest_api:v1.0

###Push All Images from Docker Compose (docker-compose.yaml)
#  docker-compose push

### Verify the Push
#  docker-compose images
#  docker-compose ps
#  docker-compose logs
#  docker-compose logs -f
#  docker search jehad950/flight_search_rest_api