package com.flight_search.domain.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.context.annotation.Profile;

import java.util.Collection;

/**
 * Represents an airport entity in the database.
 */
@Profile("test")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity
@Table(name = "airports")
public class AirportEntity {

    /**
     * The unique identifier of the airport.
     * This field is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "airports_seq")
    @SequenceGenerator(name = "airports_seq", sequenceName = "custom_airports_id_seq", allocationSize = 1)
    private Long id;

    /**
     * The city where the airport is located.
     * This field cannot be null.
     */
    @NotNull
    private String city;

}
